api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Dto']
    title: APPCC Demo ES API
    version: 0.1.0-mvp
    exception_to_status:
        App\Exception\BusinessRuleException: 422
        Symfony\Component\Serializer\Exception\UnexpectedValueException: 400
        Symfony\Component\Serializer\Exception\ExtraAttributesException: 400
    defaults:
        stateless: true
        security: "is_granted('ROLE_USER')"
        security_post_denormalize: "is_granted('APPCC_WRITE', object)"
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin', 'X-Establecimiento-Id']
