<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260911130812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crear la entidad fiscal con NIF único y fechas de creación y actualización.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE entidad_fiscal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(255) NOT NULL, nombre_comercial VARCHAR(150) DEFAULT NULL, razon_social VARCHAR(200) DEFAULT NULL, nombre VARCHAR(100) DEFAULT NULL, apellidos VARCHAR(150) DEFAULT NULL, nif VARCHAR(20) NOT NULL, direccion VARCHAR(255) NOT NULL, codigo_postal VARCHAR(10) NOT NULL, localidad VARCHAR(120) NOT NULL, provincia VARCHAR(120) NOT NULL, telefono VARCHAR(30) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, activo BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_725BAE4CADE62BBB ON entidad_fiscal (nif)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE entidad_fiscal');
    }
}
