<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260916090000 extends AbstractMigration
{
    public function getDescription(): string { return 'Subidas privadas temporales, confirmación auditable e inmutabilidad de registros y evidencias.'; }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform, 'Esta migración requiere PostgreSQL.');
        $this->addSql('ALTER TABLE registro_appcc ADD confirmado_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE registro_appcc ADD confirmado_por_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE registro_appcc ADD version_declaracion_firma VARCHAR(32) DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_registro_confirmado_por ON registro_appcc (confirmado_por_id)');
        $this->addSql('ALTER TABLE registro_appcc ADD CONSTRAINT fk_registro_confirmado_por FOREIGN KEY (confirmado_por_id) REFERENCES usuario (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE registro_appcc ADD CONSTRAINT chk_registro_confirmacion CHECK ((confirmado_at IS NULL) = (confirmado_por_id IS NULL))');
        $this->addSql('ALTER TABLE registro_appcc ADD CONSTRAINT chk_registro_firmante CHECK (confirmado_por_id IS NULL OR confirmado_por_id = usuario_id)');
        $this->addSql('CREATE TABLE subida_temporal_evidencia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, usuario_id INT NOT NULL, establecimiento_id INT NOT NULL, tipo VARCHAR(20) NOT NULL, storage_key VARCHAR(512) NOT NULL, nombre_original VARCHAR(255) NOT NULL, mime_type VARCHAR(127) NOT NULL, tamano_bytes BIGINT NOT NULL, hash_sha256 VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consumida_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_subida_token ON subida_temporal_evidencia (token_hash)');
        $this->addSql('CREATE INDEX idx_subida_expiracion ON subida_temporal_evidencia (expires_at)');
        $this->addSql('CREATE INDEX idx_subida_usuario ON subida_temporal_evidencia (usuario_id)');
        $this->addSql('CREATE INDEX idx_subida_establecimiento ON subida_temporal_evidencia (establecimiento_id)');
        $this->addSql('ALTER TABLE subida_temporal_evidencia ADD CONSTRAINT fk_subida_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE subida_temporal_evidencia ADD CONSTRAINT fk_subida_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimiento (id) ON DELETE RESTRICT');
        $this->addSql("ALTER TABLE subida_temporal_evidencia ADD CONSTRAINT chk_subida_archivo CHECK (tamano_bytes > 0 AND hash_sha256 ~ '^[a-f0-9]{64}$' AND token_hash ~ '^[a-f0-9]{64}$' AND storage_key ~ '^temporal/[a-f0-9]{64}$' AND ((tipo = 'foto' AND mime_type IN ('image/jpeg', 'image/png', 'image/webp')) OR (tipo = 'documento' AND mime_type = 'application/pdf')))");
        $this->addSql('ALTER TABLE subida_temporal_evidencia ADD CONSTRAINT chk_subida_consumo CHECK (consumida_at IS NULL OR consumida_at < expires_at)');
        $this->addSql(<<<'SQL'
CREATE FUNCTION appcc_documento_inmutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Los registros y evidencias históricos son inmutables' USING ERRCODE = '23514';
END $$
SQL);
        $this->addSql('CREATE TRIGGER trg_registro_inmutable BEFORE UPDATE OR DELETE ON registro_appcc FOR EACH ROW EXECUTE FUNCTION appcc_documento_inmutable()');
        $this->addSql('CREATE TRIGGER trg_evidencia_inmutable BEFORE UPDATE OR DELETE ON evidencia FOR EACH ROW EXECUTE FUNCTION appcc_documento_inmutable()');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('LOCK TABLE registro_appcc, subida_temporal_evidencia IN ACCESS EXCLUSIVE MODE');
        $this->addSql("DO $$ BEGIN IF EXISTS (SELECT 1 FROM registro_appcc WHERE confirmado_at IS NOT NULL) OR EXISTS (SELECT 1 FROM subida_temporal_evidencia) THEN RAISE EXCEPTION 'Reversión bloqueada: hay confirmaciones o subidas que deben conservarse'; END IF; END $$");
        $this->addSql('DROP TRIGGER trg_evidencia_inmutable ON evidencia');
        $this->addSql('DROP TRIGGER trg_registro_inmutable ON registro_appcc');
        $this->addSql('DROP FUNCTION appcc_documento_inmutable()');
        $this->addSql('DROP TABLE subida_temporal_evidencia');
        $this->addSql('ALTER TABLE registro_appcc DROP CONSTRAINT chk_registro_confirmacion');
        $this->addSql('ALTER TABLE registro_appcc DROP CONSTRAINT chk_registro_firmante');
        $this->addSql('ALTER TABLE registro_appcc DROP confirmado_at, DROP confirmado_por_id, DROP version_declaracion_firma');
    }
}
