<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260911151914 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Añadir las configuraciones de entidad fiscal y establecimiento con relación única a su titular.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE configuracion_entidad_fiscal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, logo_path VARCHAR(255) DEFAULT NULL, idioma VARCHAR(10) DEFAULT \'es\' NOT NULL, zona_horaria VARCHAR(100) DEFAULT \'Europe/Madrid\' NOT NULL, notificaciones_email BOOLEAN DEFAULT true NOT NULL, notificar_incidencias BOOLEAN DEFAULT true NOT NULL, notificar_tareas_pendientes BOOLEAN DEFAULT true NOT NULL, resumen_diario_email BOOLEAN DEFAULT false NOT NULL, dias_conservacion_registros INT DEFAULT NULL, permitir_gestion_multi_establecimiento BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, entidad_fiscal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4865284CD3FCA8FD ON configuracion_entidad_fiscal (entidad_fiscal_id)');
        $this->addSql('CREATE TABLE configuracion_establecimiento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hora_inicio_jornada TIME(0) WITHOUT TIME ZONE DEFAULT NULL, hora_fin_jornada TIME(0) WITHOUT TIME ZONE DEFAULT NULL, requiere_firma_registro BOOLEAN DEFAULT false NOT NULL, permite_registros_atrasados BOOLEAN DEFAULT false NOT NULL, maximo_minutos_registro_atrasado INT DEFAULT NULL, genera_incidencia_automatica BOOLEAN DEFAULT true NOT NULL, requiere_observacion_no_conforme BOOLEAN DEFAULT true NOT NULL, requiere_foto_no_conforme BOOLEAN DEFAULT false NOT NULL, permitir_cerrar_incidencia_sin_accion BOOLEAN DEFAULT false NOT NULL, avisar_tareas_pendientes BOOLEAN DEFAULT true NOT NULL, minutos_aviso_tarea INT DEFAULT 30 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, establecimiento_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_949EEFF871B61351 ON configuracion_establecimiento (establecimiento_id)');
        $this->addSql('ALTER TABLE configuracion_entidad_fiscal ADD CONSTRAINT FK_4865284CD3FCA8FD FOREIGN KEY (entidad_fiscal_id) REFERENCES entidad_fiscal (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE configuracion_establecimiento ADD CONSTRAINT FK_949EEFF871B61351 FOREIGN KEY (establecimiento_id) REFERENCES establecimiento (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE configuracion_entidad_fiscal DROP CONSTRAINT FK_4865284CD3FCA8FD');
        $this->addSql('ALTER TABLE configuracion_establecimiento DROP CONSTRAINT FK_949EEFF871B61351');
        $this->addSql('DROP TABLE configuracion_entidad_fiscal');
        $this->addSql('DROP TABLE configuracion_establecimiento');
    }
}
