<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260911132708 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Añadir el modelo MVP APPCC sobre la entidad fiscal de la migración anterior.';
    }

    public function up(Schema $schema): void
    {
        // entidad_fiscal se crea en Version20260911130812.
        $this->addSql('CREATE TABLE accion_correctiva (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, descripcion TEXT NOT NULL, resultado TEXT DEFAULT NULL, fecha_hora TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, incidencia_id INT NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_15E3EFAEE1605BE2 ON accion_correctiva (incidencia_id)');
        $this->addSql('CREATE INDEX IDX_15E3EFAEDB38439E ON accion_correctiva (usuario_id)');
        $this->addSql('CREATE TABLE establecimiento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(180) NOT NULL, tipo_actividad VARCHAR(255) NOT NULL, direccion VARCHAR(255) NOT NULL, codigo_postal VARCHAR(10) NOT NULL, localidad VARCHAR(120) NOT NULL, provincia VARCHAR(120) NOT NULL, telefono VARCHAR(30) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, registro_sanitario VARCHAR(100) DEFAULT NULL, activo BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, entidad_fiscal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_94A4D17ED3FCA8FD ON establecimiento (entidad_fiscal_id)');
        $this->addSql('CREATE TABLE incidencia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(180) NOT NULL, descripcion TEXT NOT NULL, gravedad VARCHAR(255) NOT NULL, estado VARCHAR(255) DEFAULT \'abierta\' NOT NULL, fecha_apertura TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_cierre TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, establecimiento_id INT NOT NULL, registro_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C7C6728C71B61351 ON incidencia (establecimiento_id)');
        $this->addSql('CREATE INDEX IDX_C7C6728C39C50FAE ON incidencia (registro_id)');
        $this->addSql('CREATE TABLE plan_control (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(255) NOT NULL, nombre VARCHAR(180) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, establecimiento_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5364644371B61351 ON plan_control (establecimiento_id)');
        $this->addSql('CREATE TABLE plantilla_appcc (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(180) NOT NULL, tipo_actividad VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, configuracion JSON NOT NULL, activa BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE punto_control (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(180) NOT NULL, tipo VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN DEFAULT true NOT NULL, establecimiento_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8B02081471B61351 ON punto_control (establecimiento_id)');
        $this->addSql('CREATE TABLE registro_appcc (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha_hora TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conforme BOOLEAN NOT NULL, valor_numerico NUMERIC(12, 3) DEFAULT NULL, datos JSON DEFAULT NULL, observaciones TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tarea_id INT NOT NULL, establecimiento_id INT NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_61A0686E6D5BDFE1 ON registro_appcc (tarea_id)');
        $this->addSql('CREATE INDEX IDX_61A0686E71B61351 ON registro_appcc (establecimiento_id)');
        $this->addSql('CREATE INDEX IDX_61A0686EDB38439E ON registro_appcc (usuario_id)');
        $this->addSql('CREATE TABLE tarea_appcc (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(180) NOT NULL, descripcion TEXT DEFAULT NULL, frecuencia VARCHAR(255) NOT NULL, hora_prevista TIME(0) WITHOUT TIME ZONE DEFAULT NULL, limite_minimo NUMERIC(12, 3) DEFAULT NULL, limite_maximo NUMERIC(12, 3) DEFAULT NULL, unidad VARCHAR(30) DEFAULT NULL, instrucciones TEXT DEFAULT NULL, configuracion JSON DEFAULT NULL, obligatoria BOOLEAN DEFAULT true NOT NULL, activa BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, plan_control_id INT NOT NULL, establecimiento_id INT NOT NULL, punto_control_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8CE9D99B5FD3FD18 ON tarea_appcc (plan_control_id)');
        $this->addSql('CREATE INDEX IDX_8CE9D99B71B61351 ON tarea_appcc (establecimiento_id)');
        $this->addSql('CREATE INDEX IDX_8CE9D99B5BB92533 ON tarea_appcc (punto_control_id)');
        $this->addSql('CREATE TABLE usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(100) NOT NULL, apellidos VARCHAR(150) NOT NULL, email VARCHAR(180) NOT NULL, activo BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2265B05DE7927C74 ON usuario (email)');
        $this->addSql('CREATE TABLE usuario_establecimiento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rol VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT true NOT NULL, usuario_id INT NOT NULL, establecimiento_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_usuario_establecimiento ON usuario_establecimiento (usuario_id, establecimiento_id)');
        $this->addSql('CREATE INDEX IDX_7110F23FDB38439E ON usuario_establecimiento (usuario_id)');
        $this->addSql('CREATE INDEX IDX_7110F23F71B61351 ON usuario_establecimiento (establecimiento_id)');
        $this->addSql('ALTER TABLE accion_correctiva ADD CONSTRAINT FK_15E3EFAEE1605BE2 FOREIGN KEY (incidencia_id) REFERENCES incidencia (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE accion_correctiva ADD CONSTRAINT FK_15E3EFAEDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE establecimiento ADD CONSTRAINT FK_94A4D17ED3FCA8FD FOREIGN KEY (entidad_fiscal_id) REFERENCES entidad_fiscal (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incidencia ADD CONSTRAINT FK_C7C6728C71B61351 FOREIGN KEY (establecimiento_id) REFERENCES establecimiento (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incidencia ADD CONSTRAINT FK_C7C6728C39C50FAE FOREIGN KEY (registro_id) REFERENCES registro_appcc (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE plan_control ADD CONSTRAINT FK_5364644371B61351 FOREIGN KEY (establecimiento_id) REFERENCES establecimiento (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE punto_control ADD CONSTRAINT FK_8B02081471B61351 FOREIGN KEY (establecimiento_id) REFERENCES establecimiento (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE registro_appcc ADD CONSTRAINT FK_61A0686E6D5BDFE1 FOREIGN KEY (tarea_id) REFERENCES tarea_appcc (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE registro_appcc ADD CONSTRAINT FK_61A0686E71B61351 FOREIGN KEY (establecimiento_id) REFERENCES establecimiento (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE registro_appcc ADD CONSTRAINT FK_61A0686EDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tarea_appcc ADD CONSTRAINT FK_8CE9D99B5FD3FD18 FOREIGN KEY (plan_control_id) REFERENCES plan_control (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tarea_appcc ADD CONSTRAINT FK_8CE9D99B71B61351 FOREIGN KEY (establecimiento_id) REFERENCES establecimiento (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tarea_appcc ADD CONSTRAINT FK_8CE9D99B5BB92533 FOREIGN KEY (punto_control_id) REFERENCES punto_control (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE usuario_establecimiento ADD CONSTRAINT FK_7110F23FDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE usuario_establecimiento ADD CONSTRAINT FK_7110F23F71B61351 FOREIGN KEY (establecimiento_id) REFERENCES establecimiento (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE accion_correctiva DROP CONSTRAINT FK_15E3EFAEE1605BE2');
        $this->addSql('ALTER TABLE accion_correctiva DROP CONSTRAINT FK_15E3EFAEDB38439E');
        $this->addSql('ALTER TABLE establecimiento DROP CONSTRAINT FK_94A4D17ED3FCA8FD');
        $this->addSql('ALTER TABLE incidencia DROP CONSTRAINT FK_C7C6728C71B61351');
        $this->addSql('ALTER TABLE incidencia DROP CONSTRAINT FK_C7C6728C39C50FAE');
        $this->addSql('ALTER TABLE plan_control DROP CONSTRAINT FK_5364644371B61351');
        $this->addSql('ALTER TABLE punto_control DROP CONSTRAINT FK_8B02081471B61351');
        $this->addSql('ALTER TABLE registro_appcc DROP CONSTRAINT FK_61A0686E6D5BDFE1');
        $this->addSql('ALTER TABLE registro_appcc DROP CONSTRAINT FK_61A0686E71B61351');
        $this->addSql('ALTER TABLE registro_appcc DROP CONSTRAINT FK_61A0686EDB38439E');
        $this->addSql('ALTER TABLE tarea_appcc DROP CONSTRAINT FK_8CE9D99B5FD3FD18');
        $this->addSql('ALTER TABLE tarea_appcc DROP CONSTRAINT FK_8CE9D99B71B61351');
        $this->addSql('ALTER TABLE tarea_appcc DROP CONSTRAINT FK_8CE9D99B5BB92533');
        $this->addSql('ALTER TABLE usuario_establecimiento DROP CONSTRAINT FK_7110F23FDB38439E');
        $this->addSql('ALTER TABLE usuario_establecimiento DROP CONSTRAINT FK_7110F23F71B61351');
        $this->addSql('DROP TABLE accion_correctiva');
        $this->addSql('DROP TABLE establecimiento');
        $this->addSql('DROP TABLE incidencia');
        $this->addSql('DROP TABLE plan_control');
        $this->addSql('DROP TABLE plantilla_appcc');
        $this->addSql('DROP TABLE punto_control');
        $this->addSql('DROP TABLE registro_appcc');
        $this->addSql('DROP TABLE tarea_appcc');
        $this->addSql('DROP TABLE usuario');
        $this->addSql('DROP TABLE usuario_establecimiento');
    }
}
