<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/** Generada por Doctrine y revisada: migración incremental con backfill y guardas. */
final class Version20260912083224 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Separar ejecuciones de definiciones; conservar registros; añadir evidencias, historial e índices.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform, 'Esta migración requiere PostgreSQL.');
        $this->addSql('LOCK TABLE registro_appcc, incidencia, tarea_appcc IN SHARE ROW EXCLUSIVE MODE');
        // No inventar fechas ni fusionar históricos para satisfacer una nueva unicidad.
        $this->addSql(<<<'SQL'
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM registro_appcc GROUP BY tarea_id, fecha_hora HAVING count(*) > 1) THEN
        RAISE EXCEPTION 'Hay registros con la misma definición y fecha: resolver su identidad antes de migrar, sin borrarlos';
    END IF;
    IF EXISTS (SELECT 1 FROM incidencia WHERE registro_id IS NOT NULL GROUP BY registro_id HAVING count(*) > 1) THEN
        RAISE EXCEPTION 'Hay varias incidencias por registro: se requiere una decisión de conservación antes de migrar';
    END IF;
    IF EXISTS (SELECT 1 FROM registro_appcc r JOIN tarea_appcc t ON t.id = r.tarea_id WHERE r.establecimiento_id <> t.establecimiento_id) THEN
        RAISE EXCEPTION 'Hay registros cuyo establecimiento no coincide con su definición';
    END IF;
END $$
SQL);
        $this->addSql('CREATE TABLE evidencia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(20) NOT NULL, storage_key VARCHAR(512) NOT NULL, nombre_original VARCHAR(255) NOT NULL, mime_type VARCHAR(127) NOT NULL, tamano_bytes BIGINT NOT NULL, hash_sha256 VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, registro_id INT DEFAULT NULL, incidencia_id INT DEFAULT NULL, subida_por_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_59B9807C39C50FAE ON evidencia (registro_id)');
        $this->addSql('CREATE INDEX IDX_59B9807CE1605BE2 ON evidencia (incidencia_id)');
        $this->addSql('CREATE INDEX IDX_59B9807C11CCD0D4 ON evidencia (subida_por_id)');
        $this->addSql('CREATE TABLE historial_incidencia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, estado_anterior VARCHAR(255) DEFAULT NULL, estado_nuevo VARCHAR(255) NOT NULL, comentario TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, incidencia_id INT NOT NULL, cambiado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_365AFAF6E1605BE2 ON historial_incidencia (incidencia_id)');
        $this->addSql('CREATE INDEX IDX_365AFAF698E7AFEF ON historial_incidencia (cambiado_por_id)');
        $this->addSql('CREATE TABLE tarea_programada (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha_programada TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_limite TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estado VARCHAR(20) DEFAULT \'pendiente\' NOT NULL, completada_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tarea_id INT NOT NULL, establecimiento_id INT NOT NULL, asignado_a_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_programada_agenda ON tarea_programada (establecimiento_id, estado, fecha_programada)');
        $this->addSql('CREATE UNIQUE INDEX uniq_programada_tarea_fecha ON tarea_programada (tarea_id, fecha_programada)');
        $this->addSql('CREATE INDEX IDX_6A4610C46D5BDFE1 ON tarea_programada (tarea_id)');
        $this->addSql('CREATE INDEX IDX_6A4610C471B61351 ON tarea_programada (establecimiento_id)');
        $this->addSql('CREATE INDEX IDX_6A4610C439055ADD ON tarea_programada (asignado_a_id)');
        $this->addSql('ALTER TABLE evidencia ADD CONSTRAINT FK_59B9807C39C50FAE FOREIGN KEY (registro_id) REFERENCES registro_appcc (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evidencia ADD CONSTRAINT FK_59B9807CE1605BE2 FOREIGN KEY (incidencia_id) REFERENCES incidencia (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evidencia ADD CONSTRAINT FK_59B9807C11CCD0D4 FOREIGN KEY (subida_por_id) REFERENCES usuario (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historial_incidencia ADD CONSTRAINT FK_365AFAF6E1605BE2 FOREIGN KEY (incidencia_id) REFERENCES incidencia (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historial_incidencia ADD CONSTRAINT FK_365AFAF698E7AFEF FOREIGN KEY (cambiado_por_id) REFERENCES usuario (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tarea_programada ADD CONSTRAINT FK_6A4610C46D5BDFE1 FOREIGN KEY (tarea_id) REFERENCES tarea_appcc (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tarea_programada ADD CONSTRAINT FK_6A4610C471B61351 FOREIGN KEY (establecimiento_id) REFERENCES establecimiento (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tarea_programada ADD CONSTRAINT FK_6A4610C439055ADD FOREIGN KEY (asignado_a_id) REFERENCES usuario (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_incidencia_agenda ON incidencia (establecimiento_id, estado, fecha_apertura)');
        $this->addSql('CREATE UNIQUE INDEX uniq_incidencia_registro ON incidencia (registro_id) WHERE (registro_id IS NOT NULL)');
        $this->addSql('ALTER TABLE registro_appcc DROP CONSTRAINT fk_61a0686e6d5bdfe1');
        $this->addSql('DROP INDEX idx_61a0686e6d5bdfe1');
        $this->addSql('ALTER TABLE registro_appcc ADD tarea_programada_id INT DEFAULT NULL');
        $this->addSql("INSERT INTO tarea_programada (tarea_id, establecimiento_id, asignado_a_id, fecha_programada, estado, completada_at, created_at) SELECT tarea_id, establecimiento_id, usuario_id, fecha_hora, 'completada', fecha_hora, created_at FROM registro_appcc ORDER BY id");
        $this->addSql('UPDATE registro_appcc r SET tarea_programada_id = p.id FROM tarea_programada p WHERE p.tarea_id = r.tarea_id AND p.fecha_programada = r.fecha_hora');
        $this->addSql(<<<'SQL'
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM registro_appcc WHERE tarea_programada_id IS NULL)
       OR (SELECT count(*) FROM registro_appcc) <> (SELECT count(*) FROM tarea_programada) THEN
        RAISE EXCEPTION 'Backfill incompleto: se conserva la relación anterior mediante rollback';
    END IF;
END $$
SQL);
        $this->addSql('ALTER TABLE registro_appcc ALTER tarea_programada_id SET NOT NULL');
        $this->addSql('ALTER TABLE registro_appcc DROP COLUMN tarea_id');
        $this->addSql('ALTER TABLE registro_appcc ADD CONSTRAINT FK_61A0686E259A0D32 FOREIGN KEY (tarea_programada_id) REFERENCES tarea_programada (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_61A0686E259A0D32 ON registro_appcc (tarea_programada_id)');
        $this->addSql('CREATE INDEX idx_registro_local_fecha ON registro_appcc (establecimiento_id, fecha_hora)');
        $this->addSql('CREATE INDEX idx_registro_usuario_fecha ON registro_appcc (usuario_id, fecha_hora)');
        $this->addSql('CREATE INDEX idx_tarea_local_activa ON tarea_appcc (establecimiento_id, activa)');
        $this->addSql('CREATE INDEX idx_membresia_local_activo_usuario ON usuario_establecimiento (establecimiento_id, activo, usuario_id)');
        $this->addSql('ALTER TABLE evidencia ADD CONSTRAINT chk_evidencia_parent CHECK ((registro_id IS NOT NULL) <> (incidencia_id IS NOT NULL))');
        $this->addSql('ALTER TABLE evidencia ADD CONSTRAINT chk_evidencia_size CHECK (tamano_bytes > 0)');
        $this->addSql("ALTER TABLE evidencia ADD CONSTRAINT chk_evidencia_hash CHECK (hash_sha256 IS NULL OR hash_sha256 ~ '^[a-fA-F0-9]{64}$')");
        $this->addSql('ALTER TABLE tarea_programada ADD CONSTRAINT chk_programada_fechas CHECK (fecha_limite IS NULL OR fecha_limite >= fecha_programada)');
        $this->addSql("ALTER TABLE tarea_programada ADD CONSTRAINT chk_programada_completada CHECK ((estado = 'completada') = (completada_at IS NOT NULL))");
        // No inventar autores ni transiciones históricas: una instantánea marcada como migración.
        $this->addSql("INSERT INTO historial_incidencia (incidencia_id, estado_anterior, estado_nuevo, comentario, created_at) SELECT id, NULL, estado, 'Estado observado al migrar; transiciones anteriores no disponibles.', created_at FROM incidencia");
        $this->addSql(<<<'SQL'
CREATE FUNCTION appcc_historial_inmutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'El historial de incidencia es append-only'; END $$
SQL);
        $this->addSql('CREATE TRIGGER trg_historial_inmutable BEFORE UPDATE OR DELETE ON historial_incidencia FOR EACH ROW EXECUTE FUNCTION appcc_historial_inmutable()');    }

    public function down(Schema $schema): void
    {
        // Reversible solo sin nuevos datos. Jamás descartar evidencia o historial silenciosamente.
        $this->addSql('LOCK TABLE evidencia, historial_incidencia, tarea_programada, registro_appcc IN ACCESS EXCLUSIVE MODE');
        $this->addSql(<<<'SQL'
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM evidencia) OR EXISTS (SELECT 1 FROM historial_incidencia)
       OR EXISTS (SELECT 1 FROM tarea_programada) OR EXISTS (SELECT 1 FROM registro_appcc) THEN
        RAISE EXCEPTION 'Reversión bloqueada: hay datos operativos que requieren exportación y migración inversa explícita';
    END IF;
END $$
SQL);
        $this->addSql('ALTER TABLE registro_appcc DROP CONSTRAINT FK_61A0686E259A0D32');
        $this->addSql('DROP INDEX UNIQ_61A0686E259A0D32');
        $this->addSql('ALTER TABLE registro_appcc RENAME COLUMN tarea_programada_id TO tarea_id');
        $this->addSql('ALTER TABLE registro_appcc ADD CONSTRAINT fk_61a0686e6d5bdfe1 FOREIGN KEY (tarea_id) REFERENCES tarea_appcc (id) ON DELETE RESTRICT');
        $this->addSql('CREATE INDEX idx_61a0686e6d5bdfe1 ON registro_appcc (tarea_id)');
        $this->addSql('DROP TABLE evidencia');
        $this->addSql('DROP TABLE historial_incidencia');
        $this->addSql('DROP FUNCTION appcc_historial_inmutable()');
        $this->addSql('DROP TABLE tarea_programada');
        foreach (['idx_incidencia_agenda', 'uniq_incidencia_registro', 'idx_registro_local_fecha', 'idx_registro_usuario_fecha', 'idx_tarea_local_activa', 'idx_membresia_local_activo_usuario'] as $index) {
            $this->addSql('DROP INDEX '.$index);
        }
    }
}
