<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/** Alta de identidades e invitaciones, sin modificar históricos ni credenciales existentes. */
final class Version20260913205925 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Invitaciones y tokens de contraseña inicial con integridad PostgreSQL y email normalizado.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform, 'Esta migración requiere PostgreSQL.');
        // Si hay identidades heredadas equivalentes, requieren resolución explícita; nunca fusionarlas silenciosamente.
        $normalizado = "lower(btrim(email, ' ' || chr(9) || chr(10) || chr(13) || chr(11)))";
        $this->addSql("DO $$ BEGIN IF EXISTS (SELECT 1 FROM usuario GROUP BY $normalizado HAVING count(*) > 1) THEN RAISE EXCEPTION 'Hay emails equivalentes: resolver las identidades antes de migrar'; END IF; END $$");
        $this->addSql("UPDATE usuario SET email = $normalizado WHERE email <> $normalizado");
        $this->addSql("ALTER TABLE usuario ADD CONSTRAINT chk_usuario_email_normalizado CHECK (email = $normalizado)");
        $this->addSql('CREATE TABLE invitacion_usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, rol VARCHAR(20) NOT NULL, token_hash VARCHAR(64) NOT NULL, estado VARCHAR(20) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, establecimiento_id INT NOT NULL, invitada_por_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_21189A5BB3BC57DA ON invitacion_usuario (token_hash)');
        $this->addSql('CREATE UNIQUE INDEX uniq_invitacion_pendiente ON invitacion_usuario (establecimiento_id, email) WHERE (estado = \'pendiente\')');
        $this->addSql('CREATE INDEX IDX_21189A5B71B61351 ON invitacion_usuario (establecimiento_id)');
        $this->addSql('CREATE INDEX IDX_21189A5BFBC84086 ON invitacion_usuario (invitada_por_id)');
        $this->addSql('CREATE TABLE token_configuracion_password (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consumed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8C990D61B3BC57DA ON token_configuracion_password (token_hash)');
        $this->addSql('CREATE INDEX IDX_8C990D61DB38439E ON token_configuracion_password (usuario_id)');
        $this->addSql('ALTER TABLE invitacion_usuario ADD CONSTRAINT FK_21189A5B71B61351 FOREIGN KEY (establecimiento_id) REFERENCES establecimiento (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invitacion_usuario ADD CONSTRAINT FK_21189A5BFBC84086 FOREIGN KEY (invitada_por_id) REFERENCES usuario (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE token_configuracion_password ADD CONSTRAINT FK_8C990D61DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql("ALTER TABLE invitacion_usuario ADD CONSTRAINT chk_invitacion_email CHECK (email = $normalizado)");
        $this->addSql("ALTER TABLE invitacion_usuario ADD CONSTRAINT chk_invitacion_rol CHECK (rol IN ('admin', 'responsable', 'trabajador', 'auditor'))");
        $this->addSql("ALTER TABLE invitacion_usuario ADD CONSTRAINT chk_invitacion_estado CHECK (estado IN ('pendiente', 'aceptada', 'cancelada', 'expirada') AND ((estado = 'aceptada') = (accepted_at IS NOT NULL)) AND ((estado = 'cancelada') = (cancelled_at IS NOT NULL)))");
        $this->addSql("ALTER TABLE invitacion_usuario ADD CONSTRAINT chk_invitacion_token CHECK (token_hash ~ '^[a-f0-9]{64}$')");
        $this->addSql('ALTER TABLE invitacion_usuario ADD CONSTRAINT chk_invitacion_fechas CHECK (expires_at > created_at AND (accepted_at IS NULL OR accepted_at >= created_at) AND (cancelled_at IS NULL OR cancelled_at >= created_at))');
        $this->addSql("ALTER TABLE token_configuracion_password ADD CONSTRAINT chk_password_token CHECK (token_hash ~ '^[a-f0-9]{64}$')");
        $this->addSql('ALTER TABLE token_configuracion_password ADD CONSTRAINT chk_password_fechas CHECK (expires_at > created_at AND (consumed_at IS NULL OR consumed_at >= created_at))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql("DO $$ BEGIN IF EXISTS (SELECT 1 FROM invitacion_usuario) OR EXISTS (SELECT 1 FROM token_configuracion_password) THEN RAISE EXCEPTION 'Reversión bloqueada: conservar invitaciones y tokens mediante una migración inversa explícita'; END IF; END $$");
        $this->addSql('ALTER TABLE usuario DROP CONSTRAINT chk_usuario_email_normalizado');
        $this->addSql('ALTER TABLE invitacion_usuario DROP CONSTRAINT FK_21189A5B71B61351');
        $this->addSql('ALTER TABLE invitacion_usuario DROP CONSTRAINT FK_21189A5BFBC84086');
        $this->addSql('ALTER TABLE token_configuracion_password DROP CONSTRAINT FK_8C990D61DB38439E');
        $this->addSql('DROP TABLE invitacion_usuario');
        $this->addSql('DROP TABLE token_configuracion_password');
    }
}
