<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260922090000 extends AbstractMigration
{
    public function getDescription(): string { return 'Catálogo e idempotencia de plantillas, controles pendientes de límites y foto obligatoria para todos los establecimientos.'; }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform, 'Esta migración requiere PostgreSQL.');
        $this->addSql('ALTER TABLE plantilla_appcc ADD codigo VARCHAR(80) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_plantilla_codigo ON plantilla_appcc (codigo)');
        $this->addSql('CREATE TABLE aplicacion_plantilla_appcc (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plantilla_id INT NOT NULL, establecimiento_id INT NOT NULL, resultado JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_plantilla_local ON aplicacion_plantilla_appcc (plantilla_id, establecimiento_id)');
        $this->addSql('CREATE INDEX idx_aplicacion_plantilla ON aplicacion_plantilla_appcc (plantilla_id)');
        $this->addSql('CREATE INDEX idx_aplicacion_local ON aplicacion_plantilla_appcc (establecimiento_id)');
        $this->addSql('ALTER TABLE aplicacion_plantilla_appcc ADD CONSTRAINT fk_aplicacion_plantilla FOREIGN KEY (plantilla_id) REFERENCES plantilla_appcc (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE aplicacion_plantilla_appcc ADD CONSTRAINT fk_aplicacion_local FOREIGN KEY (establecimiento_id) REFERENCES establecimiento (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE tarea_appcc ADD requiere_limites BOOLEAN DEFAULT false NOT NULL');
        $this->addSql(<<<'SQL'
ALTER TABLE tarea_appcc ADD CONSTRAINT chk_tarea_limites_configurados CHECK (
    NOT activa OR NOT requiere_limites OR (
        COALESCE(configuracion->>'tipoRespuesta', '') = 'numero'
        AND (limite_minimo IS NOT NULL OR limite_maximo IS NOT NULL)
        AND length(trim(COALESCE(unidad, ''))) > 0 AND length(trim(COALESCE(instrucciones, ''))) > 0
        AND (limite_minimo IS NULL OR limite_maximo IS NULL OR limite_minimo <= limite_maximo)
    )
)
SQL);
        $this->addSql('UPDATE configuracion_establecimiento SET requiere_foto_no_conforme = true WHERE requiere_foto_no_conforme = false');
        $this->addSql('ALTER TABLE configuracion_establecimiento ALTER requiere_foto_no_conforme SET DEFAULT true');
        $this->addSql('ALTER TABLE configuracion_establecimiento ADD CONSTRAINT chk_config_foto_obligatoria CHECK (requiere_foto_no_conforme)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('LOCK TABLE aplicacion_plantilla_appcc, tarea_appcc IN ACCESS EXCLUSIVE MODE');
        $this->addSql("DO $$ BEGIN IF EXISTS (SELECT 1 FROM aplicacion_plantilla_appcc) OR EXISTS (SELECT 1 FROM tarea_appcc WHERE requiere_limites) THEN RAISE EXCEPTION 'Reversión bloqueada: hay aplicaciones o controles configurables que deben conservarse'; END IF; END $$");
        $this->addSql('DROP TABLE aplicacion_plantilla_appcc');
        $this->addSql('ALTER TABLE tarea_appcc DROP CONSTRAINT chk_tarea_limites_configurados');
        $this->addSql('ALTER TABLE tarea_appcc DROP requiere_limites');
        $this->addSql('ALTER TABLE plantilla_appcc DROP codigo');
        $this->addSql('ALTER TABLE configuracion_establecimiento DROP CONSTRAINT chk_config_foto_obligatoria');
        $this->addSql('ALTER TABLE configuracion_establecimiento ALTER requiere_foto_no_conforme SET DEFAULT false');
        // No desactivar fotos de los establecimientos al revertir el esquema.
    }
}
