variables_order=EGPCS
expose_php=Off
display_errors=Off
log_errors=On
error_log=/proc/self/fd/2
upload_max_filesize=12M
post_max_size=24M
memory_limit=256M
opcache.enable=1
opcache.validate_timestamps=0
